version: '2'
services:
    mariadb:
        image: 'bitnami/mariadb:10.3'
        environment:
            - MARIADB_ROOT_PASSWORD=bitnami
        volumes:
            - 'mariadb_data:/bitnami'
    phpmyadmin:
        image: 'bitnami/phpmyadmin:4'
        ports:
            - '80:80'
            - '443:443'
        depends_on:
            - mariadb
        volumes:
            - 'phpmyadmin_data:/bitnami'
volumes:
    mariadb_data:
        driver: local
    phpmyadmin_data:
        driver: local
